### ISSUE TITLE
Import Failure Error 80160000

### ISSUE THREAD

**Issue by harryepstein** [aboodh95/CountryCitySelectorPCF#4]
FYI current build is failing to import in vanilla 365 CE trial. Undocumented error code 80160000

**Comment by aboodh95** [comment]
Hi @harryepstein , put in your mind that you have to change the allowed attachment size, please read this and apply the fix, then try to import 
[https://community.dynamics.com/crm/b/crminthefield/posts/caveats-of-setting-the-maximum-file-size-limits-for-attachments-in-crm-2011](https://community.dynamics.com/crm/b/crminthefield/posts/caveats-of-setting-the-maximum-file-size-limits-for-attachments-in-crm-2011)

**Comment by AJ46CODER** [comment]
Hi @aboodh95 can you help me fix error code : 80160000, while importing a custom control. The above link for the fix is empty.

**Comment by aboodh95** [comment]
Hi @AJ46CODER ,

Sorry for that, try [this](https://nishantrana.me/2019/07/17/what-is-the-maximum-file-size-limit-for-attachments-in-dynamics-365-on-premise-v9/)
